version: Build {build}

skip_non_tags: true

build:
    verbosity: minimal

environment:
    matrix:
        - PYTHON: "C:\\Python35"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "python --version"
    - "pip install -r requirements.txt"
    - "pip install pyinstaller"

build_script:
    - "python -c \"from pycamv import proteowizard ; proteowizard.fetch_proteowizard()\""
    - "pyinstaller pycamv.spec"

test_script:
    - "python setup.py test"

artifacts:
    - path: dist\PyCAMVerter.exe
      name: PyCAMVerter

deploy:
    - provider: GitHub
      description: ""
      artifact: PyCAMVerter
      draft: false
      prerelease: false
      on:
        appveyor_repo_tag: true
      auth_token:
        secure: +GzJ//tQ7T8IYqT0tFSseDQ7N5+HfGrh6pv4DHVTMxy3fhd5KYYXUfhgXkqoCIfn
