version: Build {build}

skip_non_tags: true

build:
    verbosity: minimal

environment:
    matrix:
        - PYTHON: "C:\\Python36-x64"

install:
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "python --version"
    - "pip install -r requirements.txt"
    - "pip install git+git://github.com/pyinstaller/pyinstaller.git@develop"
    - "mkdir obo"
    - ps: Start-FileDownload 'http://data.bioontology.org/ontologies/MS/submissions/116/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb' -FileName obo\obo.psi-ms-4.0.1.obo

build_script:
    - "python -c \"from pycamv import proteowizard ; proteowizard.fetch_proteowizard()\""
    - "pyinstaller pycamv.spec"

test_script:
    - "python setup.py test"

artifacts:
    - path: dist\PyCAMVerter.exe
      name: PyCAMVerter

deploy:
    - provider: GitHub
      description: ""
      artifact: PyCAMVerter
      draft: false
      prerelease: false
      on:
        appveyor_repo_tag: true
      auth_token:
        secure: +GzJ//tQ7T8IYqT0tFSseDQ7N5+HfGrh6pv4DHVTMxy3fhd5KYYXUfhgXkqoCIfn
